/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import controller.ControllerInput;

/**
 *
 * @author LENOVO
 */
public class InsertDataView extends javax.swing.JFrame {
    ControllerInput controllerInput = new ControllerInput(this);

    /**
     * Creates new form InsertDataView
     */
    public InsertDataView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        NavbarTitle = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MataKuliah = new javax.swing.JPanel();
        PPBO = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        PSCPK = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        RPL = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        SCPK = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        TECHNO = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AA = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AOK = new javax.swing.JComboBox<>();
        OPK = new javax.swing.JComboBox<>();
        PBO = new javax.swing.JComboBox<>();
        PKN = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        DataMahasiswa = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        InputNama = new javax.swing.JTextField();
        InputNIM = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        TambahData = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(16, 24, 32));

        NavbarTitle.setBackground(new java.awt.Color(16, 24, 32));
        NavbarTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 231, 21), 3, true));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 231, 21));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Input Data Nilai Mahasiswa");

        jLabel14.setFont(new java.awt.Font("Source Code Pro", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 231, 21));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Semester IV");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 231, 21), 0, true));

        javax.swing.GroupLayout NavbarTitleLayout = new javax.swing.GroupLayout(NavbarTitle);
        NavbarTitle.setLayout(NavbarTitleLayout);
        NavbarTitleLayout.setHorizontalGroup(
            NavbarTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NavbarTitleLayout.setVerticalGroup(
            NavbarTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavbarTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addGroup(NavbarTitleLayout.createSequentialGroup()
                        .addGroup(NavbarTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        MataKuliah.setBackground(new java.awt.Color(16, 24, 32));
        MataKuliah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 231, 21), 3, true));
        MataKuliah.setForeground(new java.awt.Color(255, 255, 255));

        PPBO.setBackground(new java.awt.Color(255, 255, 255));
        PPBO.setEditable(true);
        PPBO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nilai", "A", "B+", "B", "C+", "C", "D", "E" }));
        PPBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPBOActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prak. Sistem Cerdas dan Pendukung Keputusan");

        PSCPK.setBackground(new java.awt.Color(255, 255, 255));
        PSCPK.setEditable(true);
        PSCPK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilh Nilai", "A", "B+", "B", "C+", "C", "D", "E" }));
        PSCPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSCPKActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rekayasa Perangkat Lunak");

        RPL.setBackground(new java.awt.Color(255, 255, 255));
        RPL.setEditable(true);
        RPL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nilai", "A", "B+", "B", "C+", "C", "D", "E" }));
        RPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPLActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sistem Cerdas dan Pendukung Keputusan");

        SCPK.setBackground(new java.awt.Color(255, 255, 255));
        SCPK.setEditable(true);
        SCPK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nilai", "A", "B+", "B", "C+", "C", "D", "E" }));
        SCPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCPKActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Technopreneurship");

        TECHNO.setBackground(new java.awt.Color(255, 255, 255));
        TECHNO.setEditable(true);
        TECHNO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nilai", "A", "B+", "B", "C+", "C", "D", "E" }));
        TECHNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TECHNOActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Analisa Algoritma");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Arsitektur dan Organisasi Komputer");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pendidikan Kewarganegaraan");

        AA.setBackground(new java.awt.Color(255, 255, 255));
        AA.setEditable(true);
        AA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nilai", "A", "B+", "B", "C+", "C", "D", "E" }));
        AA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AAActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Otomata Dan Pengantar Kompilasi");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pemrograman Berorientasi Objek");

        AOK.setBackground(new java.awt.Color(255, 255, 255));
        AOK.setEditable(true);
        AOK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nilai", "A", "B+", "B", "C+", "C", "D", "E" }));
        AOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AOKActionPerformed(evt);
            }
        });

        OPK.setBackground(new java.awt.Color(255, 255, 255));
        OPK.setEditable(true);
        OPK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nilai", "A", "B+", "B", "C+", "C", "D", "E" }));
        OPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPKActionPerformed(evt);
            }
        });

        PBO.setBackground(new java.awt.Color(255, 255, 255));
        PBO.setEditable(true);
        PBO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nilai", "A", "B+", "B", "C+", "C", "D", "E" }));
        PBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBOActionPerformed(evt);
            }
        });

        PKN.setBackground(new java.awt.Color(255, 255, 255));
        PKN.setEditable(true);
        PKN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nilai", "A", "B+", "B", "C+", "C", "D", "E" }));
        PKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PKNActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Prak. Pemrograman Berorientasi Objek");

        javax.swing.GroupLayout MataKuliahLayout = new javax.swing.GroupLayout(MataKuliah);
        MataKuliah.setLayout(MataKuliahLayout);
        MataKuliahLayout.setHorizontalGroup(
            MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MataKuliahLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AOK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OPK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PKN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RPL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SCPK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TECHNO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PPBO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PSCPK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        MataKuliahLayout.setVerticalGroup(
            MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MataKuliahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MataKuliahLayout.createSequentialGroup()
                        .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AOK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OPK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PBO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PKN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MataKuliahLayout.createSequentialGroup()
                        .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PPBO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PSCPK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MataKuliahLayout.createSequentialGroup()
                        .addComponent(RPL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SCPK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TECHNO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DataMahasiswa.setBackground(new java.awt.Color(16, 24, 32));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama Lengkap");

        InputNama.setBackground(new java.awt.Color(16, 24, 32));
        InputNama.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        InputNama.setForeground(new java.awt.Color(255, 255, 255));
        InputNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 231, 21), 1, true));

        InputNIM.setBackground(new java.awt.Color(16, 24, 32));
        InputNIM.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        InputNIM.setForeground(new java.awt.Color(255, 255, 255));
        InputNIM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 231, 21), 1, true));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NIM");

        Reset.setBackground(new java.awt.Color(16, 24, 32));
        Reset.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Reset.setForeground(new java.awt.Color(254, 231, 21));
        Reset.setText("Reset");
        Reset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 231, 21), 3, true));
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        TambahData.setBackground(new java.awt.Color(16, 24, 32));
        TambahData.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        TambahData.setForeground(new java.awt.Color(254, 231, 21));
        TambahData.setText("Tambah");
        TambahData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 231, 21), 3, true));
        TambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahDataActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(":");

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");

        javax.swing.GroupLayout DataMahasiswaLayout = new javax.swing.GroupLayout(DataMahasiswa);
        DataMahasiswa.setLayout(DataMahasiswaLayout);
        DataMahasiswaLayout.setHorizontalGroup(
            DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataMahasiswaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(24, 24, 24)
                .addGroup(DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputNama, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addComponent(InputNIM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        DataMahasiswaLayout.setVerticalGroup(
            DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(InputNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MataKuliah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DataMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavbarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavbarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DataMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PKNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PKNActionPerformed

    private void PBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PBOActionPerformed

    private void OPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPKActionPerformed

    private void AOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AOKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AOKActionPerformed

    private void AAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AAActionPerformed

    private void TECHNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TECHNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TECHNOActionPerformed

    private void SCPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCPKActionPerformed

    private void RPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RPLActionPerformed

    private void PSCPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSCPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSCPKActionPerformed

    private void PPBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPBOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PPBOActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new MenuView().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        InputNama.setText("");
        InputNIM.setText("");
        AA.setSelectedIndex(0);
        AOK.setSelectedIndex(0);
        OPK.setSelectedIndex(0);
        PBO.setSelectedIndex(0);
        PKN.setSelectedIndex(0);
        PPBO.setSelectedIndex(0);
        PSCPK.setSelectedIndex(0);
        RPL.setSelectedIndex(0);
        SCPK.setSelectedIndex(0);
        TECHNO.setSelectedIndex(0);
    }//GEN-LAST:event_ResetActionPerformed

    private void TambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahDataActionPerformed
        // TODO add your handling code here:
        controllerInput.input();
    }//GEN-LAST:event_TambahDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertDataView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AA;
    private javax.swing.JComboBox<String> AOK;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel DataMahasiswa;
    private javax.swing.JTextField InputNIM;
    private javax.swing.JTextField InputNama;
    private javax.swing.JPanel MataKuliah;
    private javax.swing.JPanel NavbarTitle;
    private javax.swing.JComboBox<String> OPK;
    private javax.swing.JComboBox<String> PBO;
    private javax.swing.JComboBox<String> PKN;
    private javax.swing.JComboBox<String> PPBO;
    private javax.swing.JComboBox<String> PSCPK;
    private javax.swing.JComboBox<String> RPL;
    private javax.swing.JButton Reset;
    private javax.swing.JComboBox<String> SCPK;
    private javax.swing.JComboBox<String> TECHNO;
    private javax.swing.JButton TambahData;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    
    // NAMA
    public JTextField getInputNama(){
        return InputNama;
    }
    
    public void setInputNama(JTextField InputNama){
        this.InputNama = InputNama;
    }
    
    // NIM
    public JTextField getInputNIM(){
        return InputNIM;
    }
    
    public void setInputNIM(JTextField InputNIM){
        this.InputNIM = InputNIM;
    }
    
    // COMBO BOX Analisa Algoritma
    public String getAA() {
        return (String) AA.getSelectedItem();
    }
    
    public void setAA(JComboBox<String> AA) {
        this.RPL.setModel(AA.getModel());
    }
    
        // COMBO BOX Arsitektur dan Organisasi Komputer
    public String getAOK() {
        return (String) AOK.getSelectedItem();
    }
    
    public void setAOK(JComboBox<String> AOK) {
        this.AOK.setModel(AOK.getModel());
    }
    
        // COMBO BOX Otomata dan Pengantar Kompilasi
    public String getOPK() {
        return (String) OPK.getSelectedItem();
    }
    
    public void setOPK(JComboBox<String> OPK) {
        this.OPK.setModel(OPK.getModel());
    }
    
    // COMBO BOX Pemrograman Berorientasi Objek
    public String getPBO() {
        return (String) PBO.getSelectedItem();
    }
    
    public void setPBO(JComboBox<String> PBO) {
        this.PBO.setModel(PBO.getModel());
    }
        
    // COMBO BOX Pendidikan Kewarganegaraan
    public String getPKN() {
        return (String) PKN.getSelectedItem();
    }
    
    public void setPKN(JComboBox<String> PKN) {
        this.PKN.setModel(PKN.getModel());
    }
    
    // COMBO BOX Prak. Pemrograman Berorientasi Objek
    public String getPPBO() {
        return (String) PPBO.getSelectedItem();
    }
    
    public void setPPBO(JComboBox<String> PPBO) {
        this.PPBO.setModel(PPBO.getModel());
    }
    
        // COMBO BOX Prak. Sistem Cerdas dan Pendukung Keputusan
    public String getPSCPK() {
        return (String) PSCPK.getSelectedItem();
    }
    
    public void setPSCPK(JComboBox<String> PSCPK) {
        this.PSCPK.setModel(PSCPK.getModel());
    }
    
        // COMBO BOX Rekayasa Perangkat Lunak
    public String getRPL() {
        return (String) RPL.getSelectedItem();
    }
    
    public void setRPL(JComboBox<String> RPL) {
        this.RPL.setModel(RPL.getModel());
    }
    
    // COMBO BOX Sistem Cerdas dan Pendukung Keputusan
    public String getSCPK() {
        return (String) SCPK.getSelectedItem();
    }
    
    public void setSCPK(JComboBox<String> SCPK) {
        this.SCPK.setModel(SCPK.getModel());
    }
        
    // COMBO BOX Technopreneurship
    public String getTECHNO() {
        return (String) TECHNO.getSelectedItem();
    }
}
